# Generated by Django 4.2 on 2023-04-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=10)),
                ("product_name", models.CharField(max_length=15)),
                (
                    "product_size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("F", "Free"),
                        ],
                        max_length=1,
                    ),
                ),
                ("product_price", models.CharField(max_length=10)),
                ("product_desc", models.TextField()),
                ("product_quantity", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Musinsa_erp",
            },
        ),
        migrations.CreateModel(
            name="Inbound",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("inbound_quantity", models.IntegerField(default=0)),
                ("inbound_date", models.DateTimeField(auto_now_add=True)),
            ],
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="Outbound",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("outbound_quantity", models.IntegerField(default=0)),
                ("outbound_date", models.DateTimeField(auto_now_add=True)),
            ],
            bases=("products.product",),
        ),
    ]
